steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-app-builder'
    args:
      - 'pull'
      - 'us.gcr.io/${PROJECT_ID}/sample-builder:latest'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-app'
    args:
      - 'pull'
      - 'us.gcr.io/${PROJECT_ID}/sample:latest'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app-builder'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/sample-builder:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/sample-builder:$BRANCH_NAME-$REVISION_ID'
      - '--build-arg'
      - 'DIR_NAME=sample'
      - '--target'
      - 'builder'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/sample-builder:latest'
      - 'sample'
    waitFor: ['pull-app-builder', 'pull-app']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/sample:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/sample:$BRANCH_NAME-$REVISION_ID'
      - '--build-arg'
      - 'DIR_NAME=sample'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/sample:latest'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/sample-builder:latest'
      - 'sample'
    waitFor: ['build-app-builder']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-mongodb'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:$BRANCH_NAME-$REVISION_ID'
      - 'mongodb'
    waitFor: ['-']

timeout: 1800s
images:
  - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
  - 'us.gcr.io/${PROJECT_ID}/mongodb:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/${PROJECT_ID}/sample:latest'
  - 'us.gcr.io/${PROJECT_ID}/sample:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/${PROJECT_ID}/sample-builder:latest'
  - 'us.gcr.io/${PROJECT_ID}/sample-builder:$BRANCH_NAME-$REVISION_ID'
# todo:
# master のときだけ deploy
# pod -> deployment
# scale up timeout
