steps:
# sample image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-sample-image'
  args: 
  - 'build'
  - '-t'
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - '--build-arg'
  - 'project_name=sample'
  - '--cache-from'
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - 'sample'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - 'us.gcr.io/$PROJECT_ID/sample:$BRANCH_NAME-$REVISION_ID'
  waitFor: ['build-sample-image']
# mongodb image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-mongodb-image'
  args:
  - 'build' 
  - '-t'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - '--cache-from'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - 'mongodb'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - 'us.gcr.io/$PROJECT_ID/mongodb:$BRANCH_NAME-$REVISION_ID'
  waitFor: ['build-mongodb-image']
images:
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - 'us.gcr.io/$PROJECT_ID/sample:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - 'us.gcr.io/$PROJECT_ID/mongodb:$BRANCH_NAME-$REVISION_ID'

# todo: