steps:
# sample image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - '--build-arg'
  - 'project_name=sample'
  - '--cache-from'
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - 'sample'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - 'us.gcr.io/$PROJECT_ID/sample:$BRANCH_NAME-$REVISION_ID'
# mongodb image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build' 
  - '-t'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - '--cache-from'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - 'mongodb'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'us.gcr.io/$PROJECT_ID/mongodb:latest'
  - 'us.gcr.io/$PROJECT_ID/mongodb:$BRANCH_NAME-$REVISION_ID'
images:
  - 'us.gcr.io/$PROJECT_ID/sample:latest'
  - 'us.gcr.io/$PROJECT_ID/sample:$BRANCH_NAME-$REVISION_ID'

# todo:
# 複数のimageをpushする