version: 2
jobs:
  build_base:
    docker: 
      - image: alpine:3.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: set build env
          command: |
            echo "${GIT_BRANCH}"
            if [ "${GIT_BRANCH}" = "build_base_dev" ]; then 
                export BUILD_ENV="dev" 
            elif [ "${GIT_BRANCH}" = "build_base_stg" ]; then
                export BUILD_ENV="stg" 
            elif [ "${GIT_BRANCH}" = "build_base_prd" ]; then 
                export BUILD_ENV="prd" 
            else
              exit 1
            fi
      - run:
          name: echo build env
          command: |
            echo ${BUILD_ENV}

workflows:
  version: 2
  build:
    jobs:
      - build_base:
          filters:
            branches:
              only: 
                - build_base_dev
                - build_base_stg
                - build_base_prd