version: 2
jobs:
  build_base:
    docker: 
      - image: centos:7 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: set build env
          command: |
            echo "${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" = "build_base_dev" ]; then 
                echo 'export BUILD_ENV="dev"' >> ${BASH_ENV}
            elif [ "${CIRCLE_BRANCH}" = "build_base_stg" ]; then
                echo 'export BUILD_ENV="stg"' >> ${BASH_ENV}
            elif [ "${CIRCLE_BRANCH}" = "build_base_prd" ]; then 
                echo 'export BUILD_ENV="prd"' >> ${BASH_ENV}
            else
              exit 1
            fi
            source ${BASH_ENV}
            echo "${BUILD_ENV}"
      - run:
          name: echo build env
          command: |
            echo "${BUILD_ENV}"

workflows:
  version: 2
  build:
    jobs:
      - build_base:
          filters:
            branches:
              only: 
                - build_base_dev
                - build_base_stg
                - build_base_prd