version: 2.1
commands:
  set_build_env:
    parameters:
      build_env:
        type: enum
        enum: ['dev', 'stg', 'prd']
    steps:
      - run:
          name: set BUILD_ENV
          command: |
            echo -n 'export BUILD_ENV="<< parameters.build_env >>"'
            source $BASH_ENV	
            echo "BUILD_ENV is ${BUILD_ENV}"
jobs:
  build_base:
    parameters:
      build_env:
        type: enum
        enum: ['dev', 'stg', 'prd']
    docker: 
      - image: centos:7 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - set_build_env:
          build_env: << parameters.build_env >>
      - run:
          name: echo build env
          command: |
            echo "${BUILD_ENV}"

workflows:
  build:
    jobs:
      - build_base:
          build_env: dev
          filters:
            branches:
              only: 
                - build_base_dev
      - build_base:
          build_env: stg 
          filters:
            branches:
              only: 
                - build_base_stg
      - build_base:
          build_env: prd
          filters:
            branches:
              only: 
                - build_base_prd