version: 2
jobs:
  build_main_app:
    docker: 
      - image: rustlang/rust:nightly # the primary container, where your job's commands are run
    environment:
      docker_dir: sample
      image_name: rust-docker
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client and set up
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull $DOCKER_USER/$image_name
      - run:
          name: build_image
          command: |
            docker build $docker_dir -t $DOCKER_USER/$image_name
            docker push $DOCKER_USER/$image_name
  build_db:
    docker:
      - image: ubuntu:18.04
    environment:
      docker_dir: database
      image_name: mongodb
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client and set up
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull $DOCKER_USER/$image_name
      - run:
          name: build_database_image
          command: |
            docker build docker_dir -t $DOCKER_USER/$image_name
            docker push $DOCKER_USER/$image_name
workflows:
  version: 2
  build:
    jobs:
      - build_main_app
      - build_db:
          requires:
            - build_main_app