version: 2
jobs:
  build:
    docker: 
      - image: rustlang/rust:nightly # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: cargo-test-sample 
          command: cargo test
      - run:
          name: build_image
          command: |
            docker build sample -t ${DOCKER_USER}/rocket-sample
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push ${DOCKER_USER}/rocket-sample
          