version: 2.1
jobs:
  build_base:
    parameters:
      build_env:
        type: enum
        enum: ['dev', 'stg', 'prd']
    docker: 
      - image: centos:7 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: set build env
          command: |
            echo 'export BUILD_ENV="<< prameters.build_env >>"' >> ${BASH_ENV}
            source ${BASH_ENV}
            echo "${BUILD_ENV}"
      - run:
          name: echo build env
          command: |
            echo "${BUILD_ENV}"

workflows:
  build:
    jobs:
      - build_base:
          build_env: dev
          filters:
            branches:
              only: 
                - build_base_dev
      - build_base:
          build_env: stg 
          filters:
            branches:
              only: 
                - build_base_stg
      - build_base:
          build_env: prd
          filters:
            branches:
              only: 
                - build_base_prd