version: 2
jobs:
  build:
    docker: 
      - image: rustlang/rust:nightly # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: cargo-test-sample 
          command: cargo test
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: build_image
          environment:
            project_name: sample
            image_name: rust-docker
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker-compose build -f docker/docker-compose.yml
            docker push ${DOCKER_USER}/${image_name}
         # todo: project_nameを渡せるように 