version: 2
jobs:
  build_base:
    docker: 
      - image: rustlang/rust:nightly # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: echo branch name
          command: |
            echo "branch name| ${CIRCLE_BRANCH}"
            echo ${CIRCLE_BRANCH}

workflows:
  version: 2
  build:
    jobs:
      - build_base:
          filters:
            branches:
              # only: build-packer-base
              only: 
                - dev 
                - stg
                - prd 
            tags:
              ignore: /.*/
              only: /^build-packer-base/