apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api-server
  template:
    metadata:
      labels:
        app: sample-api-server 
    spec:
      containers:
      - name: sample-api-server 
        image: us.gcr.io/cloud-shell-gcloud/sample:latest
        ports:
        - containerPort: 8000
